"""
Model-download template set (shared by GPU and Neuron paths).

Produces model-download/<id>/download.sh + job.yaml. The Job is hardened
(non-root nobody UID, readOnlyRootFilesystem, drop ALL caps, HF token mounted as
a read-only Secret volume - never an env var). Gated vs non-gated models differ
only in whether the token volume + license check is present; both are handled by
the {{token_*}} placeholders the generator fills in.
"""

DOWNLOAD_SH = """\
#!/bin/bash
# ==============================================================================
# model-download/{{id}}/download.sh  - GENERATED by `oai model generate {{id}}`
#
# Downloads {{hf_id}} from HuggingFace -> S3. Friendly wrapper: oai download {{id}}
# Checks S3 first and skips if the model is already present.
# ==============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FRAMEWORK_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
source "${FRAMEWORK_ROOT}/config/config.env"

GREEN='\\033[0;32m'; YELLOW='\\033[1;33m'; RED='\\033[0;31m'; NC='\\033[0m'
log_info()  { echo -e "${GREEN}[INFO]  $(date +'%H:%M:%S')${NC} $1"; }
log_warn()  { echo -e "${YELLOW}[WARN]  $(date +'%H:%M:%S')${NC} $1"; }
log_error() { echo -e "${RED}[ERROR] $(date +'%H:%M:%S')${NC} $1"; }

MODEL_ID="{{hf_id}}"
MODEL_FOLDER="{{download_folder}}"
JOB_NAME="{{download_job_name}}"

echo ""
echo "=================================================="
echo "  MODEL DOWNLOAD - {{hf_id}}"
echo "  Bucket : s3://${MODEL_BUCKET}/${MODEL_FOLDER}/"
echo "  Token  : {{token_label}}"
echo "  Size   : ~{{size_gb}} GB"
echo "=================================================="
echo ""

log_info "Checking S3 for existing model files..."
if aws s3 ls "s3://${MODEL_BUCKET}/${MODEL_FOLDER}/" --region "${AWS_REGION}" 2>/dev/null | grep -q .; then
    log_warn "Model already exists in S3 - skipping download."
    aws s3 ls "s3://${MODEL_BUCKET}/${MODEL_FOLDER}/" --human-readable --region "${AWS_REGION}"
    exit 0
fi
{{token_check_block}}
if ! kubectl get serviceaccount "${DOWNLOAD_SERVICE_ACCOUNT}" -n "${BENCHMARK_NAMESPACE}" >/dev/null 2>&1; then
    log_error "ServiceAccount '${DOWNLOAD_SERVICE_ACCOUNT}' not found. Run: bash cluster/bootstrap.sh"
    exit 1
fi

if kubectl get job "${JOB_NAME}" -n "${BENCHMARK_NAMESPACE}" >/dev/null 2>&1; then
    log_warn "Existing job '${JOB_NAME}' found - deleting..."
    kubectl delete job "${JOB_NAME}" -n "${BENCHMARK_NAMESPACE}"
    sleep 3
fi

log_info "Applying download job..."
export MODEL_BUCKET AWS_REGION DOWNLOAD_SERVICE_ACCOUNT BENCHMARK_NAMESPACE
envsubst '${MODEL_BUCKET} ${AWS_REGION} ${DOWNLOAD_SERVICE_ACCOUNT} ${BENCHMARK_NAMESPACE}' \\
    < "${SCRIPT_DIR}/job.yaml" | kubectl apply -f -
log_info "Job '${JOB_NAME}' created."

log_info "Waiting for pod to start..."
for i in $(seq 1 30); do
    POD=$(kubectl get pods -l job-name="${JOB_NAME}" -n "${BENCHMARK_NAMESPACE}" \\
        -o jsonpath='{.items[0].metadata.name}' 2>/dev/null || true)
    [[ -n "${POD}" ]] && break
    echo -n "."; sleep 5
done
echo ""
[[ -z "${POD:-}" ]] && { log_error "Pod not found. Check: kubectl get pods -l job-name=${JOB_NAME}"; exit 1; }
log_info "Pod: ${POD}"

log_info "Streaming logs (Ctrl+C to detach - job continues)..."
kubectl logs "${POD}" -n "${BENCHMARK_NAMESPACE}" -f 2>/dev/null || \\
    kubectl logs "${POD}" -n "${BENCHMARK_NAMESPACE}" || true

log_info "Waiting for job to complete..."
kubectl wait job "${JOB_NAME}" --for=condition=complete --timeout=86400s -n "${BENCHMARK_NAMESPACE}" || {
    log_error "Job did not complete. Check: kubectl logs ${POD}"
    exit 1
}
log_info "Job completed."

log_info "Verifying S3 upload..."
aws s3 ls "s3://${MODEL_BUCKET}/${MODEL_FOLDER}/" --recursive --human-readable --region "${AWS_REGION}"

log_info "Cleaning up job..."
kubectl delete job "${JOB_NAME}" -n "${BENCHMARK_NAMESPACE}"

echo ""
echo "=================================================="
echo "  DOWNLOAD COMPLETE"
echo "  Model: s3://${MODEL_BUCKET}/${MODEL_FOLDER}/"
echo "  Next : oai deploy {{id}}"
echo "=================================================="
"""

# ---- token blocks injected into download.sh --------------------------------
TOKEN_CHECK_GATED = """\

log_info "Checking HuggingFace token secret..."
if ! kubectl get secret hf-token -n "${BENCHMARK_NAMESPACE}" >/dev/null 2>&1; then
    log_error "HuggingFace token secret not found (gated model)."
    log_error "Store it in Secrets Manager and sync via ESO, or create directly:"
    log_error "  kubectl create secret generic hf-token --from-literal=token=hf_YOURTOKEN -n ${BENCHMARK_NAMESPACE}"
    log_error "Also accept the license at: https://huggingface.co/{{hf_id}}"
    exit 1
fi
log_info "HF token secret found."
"""

TOKEN_CHECK_OPEN = ""


JOB_YAML = """\
# ==============================================================================
# model-download/{{id}}/job.yaml  - GENERATED by `oai model generate {{id}}`
#
# Kubernetes Job: downloads {{hf_id}} from HuggingFace -> S3.
# Runtime values injected via envsubst by download.sh:
#   ${MODEL_BUCKET} ${AWS_REGION} ${DOWNLOAD_SERVICE_ACCOUNT} ${BENCHMARK_NAMESPACE}
#
# Security hardening: non-root (nobody UID 65534), readOnlyRootFilesystem,
# drop ALL caps, no priv-esc, automountServiceAccountToken false, seccomp
# RuntimeDefault, CPU+mem requests/limits.{{token_security_note}}
# ==============================================================================

apiVersion: batch/v1
kind: Job
metadata:
  name: {{download_job_name}}
  namespace: ${BENCHMARK_NAMESPACE}
  labels:
    app.kubernetes.io/name: {{download_job_name}}
    app.kubernetes.io/component: model-download
    app.kubernetes.io/managed-by: oai-cli
    project: observeai-inference-optimization
    engagement: shellkode-sow
    environment: sandbox
    model: {{id}}
spec:
  backoffLimit: 2
  activeDeadlineSeconds: 86400
  ttlSecondsAfterFinished: 3600
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{download_job_name}}
        app.kubernetes.io/component: model-download
        project: observeai-inference-optimization
        engagement: shellkode-sow
        environment: sandbox
        model: {{id}}
    spec:
      restartPolicy: Never
      serviceAccountName: ${DOWNLOAD_SERVICE_ACCOUNT}
      automountServiceAccountToken: false
      hostPID: false
      hostIPC: false
      hostNetwork: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: downloader
          image: python:3.11-slim@sha256:d1053354624536b044162aaab1e418bd000ea35184fb1ae098ab3166b1072e72
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash", "-c"]
          args:
            - |
              set -euo pipefail
              MODEL_ID="{{hf_id}}"
              MODEL_FOLDER="{{download_folder}}"
              LOCAL_DIR="/tmp/${MODEL_FOLDER}"

              echo "Model  : ${MODEL_ID}"
              echo "Bucket : s3://${MODEL_BUCKET}/${MODEL_FOLDER}/"

              echo "Installing dependencies..."
              pip install --quiet --no-cache-dir --target /tmp/pip-packages \\
                  huggingface_hub==0.24.7 boto3==1.34.0
              export PYTHONPATH="/tmp/pip-packages:${PYTHONPATH:-}"

              echo "Downloading from HuggingFace..."
              python3 -c "
              import os
              from huggingface_hub import snapshot_download
              token = None
              {{token_python_block}}
              snapshot_download(
                  repo_id='${MODEL_ID}',
                  local_dir='${LOCAL_DIR}',
                  token=token,
                  ignore_patterns={{ignore_patterns}},
              )
              print('HF download complete.')
              "

              echo "Files downloaded:"; ls -lah "${LOCAL_DIR}/"

              echo "Uploading to s3://${MODEL_BUCKET}/${MODEL_FOLDER}/ ..."
              MODEL_FOLDER="${MODEL_FOLDER}" python3 << 'PYEOF'
              import boto3, os
              from pathlib import Path
              s3 = boto3.client("s3", region_name=os.environ["AWS_DEFAULT_REGION"])
              bucket = os.environ["MODEL_BUCKET"]
              folder = os.environ["MODEL_FOLDER"]
              local_dir = Path(f"/tmp/{folder}")
              files = [f for f in local_dir.rglob("*") if f.is_file() and ".cache" not in f.parts]
              print(f"Uploading {len(files)} files...")
              for i, f in enumerate(files, 1):
                  key = f"{folder}/" + str(f.relative_to(local_dir))
                  print(f"[{i}/{len(files)}] {f.name} ({f.stat().st_size/1_048_576:.1f} MB)")
                  s3.upload_file(str(f), bucket, key)
              print("Upload complete.")
              PYEOF
          env:
            - name: AWS_DEFAULT_REGION
              value: "${AWS_REGION}"
            - name: MODEL_BUCKET
              value: "${MODEL_BUCKET}"
            - name: HF_HUB_DISABLE_TELEMETRY
              value: "1"
            - name: TRANSFORMERS_CACHE
              value: "/tmp/hf-cache"
            - name: HF_HOME
              value: "/tmp/hf-home"
            - name: PIP_NO_CACHE_DIR
              value: "1"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65534
            runAsGroup: 65534
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
          resources:
            requests:
              cpu: "4"
              memory: "16Gi"
            limits:
              cpu: "8"
              memory: "32Gi"
          volumeMounts:
            - name: tmp-workspace
              mountPath: /tmp
{{token_volume_mount}}
      volumes:
        - name: tmp-workspace
          emptyDir:
            sizeLimit: {{download_scratch_gi}}Gi
{{token_volume}}
"""

# ---- token blocks injected into job.yaml ------------------------------------
TOKEN_PYTHON_GATED = """\
with open('/var/secrets/hf/token') as f:
                  token = f.read().strip()
              if not token:
                  raise RuntimeError('HF token file empty - check ExternalSecret sync')"""

TOKEN_PYTHON_OPEN = "# open model - no token required"

TOKEN_VOLUME_MOUNT_GATED = """\
            - name: hf-token-vol
              mountPath: /var/secrets/hf
              readOnly: true
"""

TOKEN_VOLUME_GATED = """\
        - name: hf-token-vol
          secret:
            secretName: hf-token
            defaultMode: 0440
"""

TOKEN_SECURITY_NOTE_GATED = """
#   - HF token mounted as a read-only Secret volume (NOT env var) [CKV_K8S_35]"""
