"""
GPU (NVIDIA vLLM DLC) template set.

Each template reproduces the platform's reviewed, hardened file. Per-model values
are {{placeholders}}; deploy-time envsubst variables (${MODEL_BUCKET}, etc.) are
left intact for the generated deploy.sh to resolve. Security hardening
(non-root, readOnlyRootFilesystem, drop ALL caps, seccomp, pinned image via
config.env, ClusterIP-only service, least-privilege serving SA) is baked in and
never exposed as a knob, so a generated model cannot accidentally weaken it.
"""

MODEL_ENV = """\
# ==============================================================================
# vllm/models/{{id}}/model.env  - GENERATED by `oai model generate {{id}}`
#
# Do not edit by hand. Edit catalog/models/{{id}}.yaml and re-run:
#   oai model generate {{id}}
#
# Model-specific configuration - sourced by deploy.sh and stop.sh.
# ==============================================================================

export MODEL_ID="{{id}}"
export MODEL_HF_ID="{{hf_id}}"
export MODEL_FOLDER="{{model_folder}}"                     # S3 folder name
export SERVED_NAME="{{served_name}}"                       # --served-model-name
export MODEL_S3_PATH="s3://${MODEL_BUCKET}/{{model_folder}}/"

export DEPLOYMENT_NAME="{{deployment_name}}"
export SERVICE_NAME="{{service_name}}"
export PVC_NAME="{{pvc_name}}"

# ── Hardware defaults (overridden per run by deploy.sh --hw / --tp) ───────────
export NODE_INSTANCE_TYPE="{{preferred_instance}}"
export TP_SIZE="{{tensor_parallel_size}}"
export GPU_COUNT="{{tensor_parallel_size}}"

export MANIFEST_PATH="configs/manifests/{{manifest_filename}}"
export PORT_FORWARD_PORT="{{port_forward_port}}"
"""

SERVICE_YAML = """\
# GENERATED by `oai model generate {{id}}` - edit catalog/models/{{id}}.yaml instead.
apiVersion: v1
kind: Service
metadata:
  name: {{service_name}}
  namespace: {{namespace}}
  labels:
    app.kubernetes.io/name: {{service_name}}
    app.kubernetes.io/component: inference-server
    project: observeai-inference-optimization
    engagement: shellkode-sow
    environment: sandbox
    model: {{id}}
spec:
  # ClusterIP only - internal cluster access via benchmark runner or port-forward.
  # No public LoadBalancer. Use ALB Ingress with auth for external access.
  type: ClusterIP
  selector:
    app: {{service_name}}
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
"""

PVC_YAML = """\
# GENERATED by `oai model generate {{id}}` - edit catalog/models/{{id}}.yaml instead.
# Metadata cache PVC - tokenizer + config files only.
# Model weights stream from S3 via Run:ai streamer - NOT stored here.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{pvc_name}}
  namespace: {{namespace}}
  labels:
    app.kubernetes.io/name: {{pvc_name}}
    app.kubernetes.io/component: metadata-cache
    project: observeai-inference-optimization
    engagement: shellkode-sow
    environment: sandbox
    model: {{id}}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 5Gi
"""

DEPLOYMENT_YAML = """\
# ==============================================================================
# vllm/models/{{id}}/deployment.yaml  - GENERATED by `oai model generate {{id}}`
#
# Do not edit by hand. Edit catalog/models/{{id}}.yaml and re-generate.
#
# Model    : {{hf_id}}
# Quant    : {{quantization}}  | max_model_len {{max_model_len}}
# GPU      : {{preferred_instance}}  (auto-provisioned by Karpenter; TP={{tensor_parallel_size}})
#
# Runtime values injected via envsubst by deploy.sh:
#   ${MODEL_BUCKET} ${BENCHMARK_NAMESPACE} ${VLLM_IMAGE} ${MODEL_FOLDER}
#   ${SERVED_NAME} ${NODE_INSTANCE_TYPE} ${TP_SIZE} ${GPU_COUNT}
#
# Security hardening (Checkov CKV_K8S_*): non-root UID 1000, readOnlyRootFilesystem,
# drop ALL caps, no privilege escalation, automountServiceAccountToken false,
# seccomp RuntimeDefault, CPU+mem requests/limits, liveness/readiness probes.
# ==============================================================================

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{deployment_name}}
  namespace: ${BENCHMARK_NAMESPACE}
  labels:
    app.kubernetes.io/name: {{deployment_name}}
    app.kubernetes.io/component: inference-server
    app.kubernetes.io/managed-by: oai-cli
    app.kubernetes.io/version: "{{id}}"
    project: observeai-inference-optimization
    engagement: shellkode-sow
    environment: sandbox
    model: {{id}}
  annotations:
    checkov.io/skip1: "CKV_K8S_43=Image digest pinned in VLLM_IMAGE via config/config.env; envsubst resolves at deploy time"
    checkov.io/skip2: "CKV_K8S_14=Image tag pinned in VLLM_IMAGE; not latest - static analysis cannot resolve envsubst variables"
    checkov.io/skip3: "CKV_K8S_15=imagePullPolicy IfNotPresent acceptable with digest-pinned image"
    checkov.io/skip4: "CKV_K8S_40=runAsUser 1000 pending vLLM UID compatibility test"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{deployment_name}}
  template:
    metadata:
      labels:
        app: {{deployment_name}}
        app.kubernetes.io/name: {{deployment_name}}
        app.kubernetes.io/component: inference-server
        project: observeai-inference-optimization
        engagement: shellkode-sow
        environment: sandbox
        model: {{id}}
    spec:
      serviceAccountName: oai-infopt-serving-sa
      automountServiceAccountToken: false

      hostPID: false
      hostIPC: false
      hostNetwork: false

      # Hardware pin - the matrix knob (deploy.sh --hw). Ties each result row to
      # an exact GPU family/size.
      nodeSelector:
        node.kubernetes.io/instance-type: ${NODE_INSTANCE_TYPE}

      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule

      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/component: benchmark-runner
                topologyKey: kubernetes.io/hostname

      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault

      terminationGracePeriodSeconds: 120

      containers:
        - name: vllm
          image: ${VLLM_IMAGE}
          imagePullPolicy: IfNotPresent

          args:
            - "--model=s3://${MODEL_BUCKET}/${MODEL_FOLDER}/"
            - "--load-format=runai_streamer"
            - "--host=0.0.0.0"
            - "--port=8000"
            - "--served-model-name=${SERVED_NAME}"
            - "--tensor-parallel-size=${TP_SIZE}"
            - "--gpu-memory-utilization={{gpu_memory_utilization}}"
            - "--max-model-len={{max_model_len}}"
            - "--max-num-seqs={{max_num_seqs}}"
            - "--max-num-batched-tokens={{max_num_batched_tokens}}"
{{extra_args_block}}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP

          envFrom:
            - configMapRef:
                name: oai-infopt-vllm-config

          env:
            - name: HOME
              value: "/tmp"
            - name: USER
              value: "vllm"
            - name: TORCHINDUCTOR_CACHE_DIR
              value: "/tmp/torchinductor_cache"

          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault

          resources:
            requests:
              cpu: "{{cpu_request}}"
              memory: "{{memory_request}}"
              nvidia.com/gpu: "${GPU_COUNT}"
            limits:
              cpu: "{{cpu_limit}}"
              memory: "{{memory_limit}}"
              nvidia.com/gpu: "${GPU_COUNT}"

          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 300
            periodSeconds: 10
            failureThreshold: 30
            timeoutSeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 360
            periodSeconds: 30
            failureThreshold: 10
            timeoutSeconds: 5

          volumeMounts:
            - name: metadata-cache
              mountPath: /metadata
            - name: dshm
              mountPath: /dev/shm
            - name: tmp
              mountPath: /tmp

      volumes:
        - name: metadata-cache
          persistentVolumeClaim:
            claimName: {{pvc_name}}
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 16Gi
        - name: tmp
          emptyDir:
            sizeLimit: 2Gi
"""


DEPLOY_SH = """\
#!/bin/bash
# ==============================================================================
# vllm/models/{{id}}/deploy.sh  - GENERATED by `oai model generate {{id}}`
#
# Generic deploy - model-specific names come from model.env.
# Usually you run this via the friendly wrapper:  oai deploy {{id}}
# but it also works standalone.
#
# Usage:
#   bash vllm/models/{{id}}/deploy.sh                  # defaults (model.env)
#   bash vllm/models/{{id}}/deploy.sh --hw g5.2xlarge  # pin GPU family/size
#   bash vllm/models/{{id}}/deploy.sh --validate       # smoke-test after ready
# ==============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FRAMEWORK_ROOT="$(cd "${SCRIPT_DIR}/../../.." && pwd)"
source "${FRAMEWORK_ROOT}/config/config.env"
source "${SCRIPT_DIR}/model.env"

: "${VLLM_IMAGE:?ERROR: VLLM_IMAGE is not set. Ensure config/config.env exports it with a pinned digest.}"

GREEN='\\033[0;32m'; YELLOW='\\033[1;33m'; RED='\\033[0;31m'; NC='\\033[0m'
log_info()  { echo -e "${GREEN}[INFO]  $(date +'%H:%M:%S')${NC} $1"; }
log_warn()  { echo -e "${YELLOW}[WARN]  $(date +'%H:%M:%S')${NC} $1"; }
log_error() { echo -e "${RED}[ERROR] $(date +'%H:%M:%S')${NC} $1"; }

VALIDATE="false"
while [[ $# -gt 0 ]]; do
    case "$1" in
        --hw)       NODE_INSTANCE_TYPE="$2"; shift 2 ;;
        --tp)       TP_SIZE="$2"; shift 2 ;;
        --validate) VALIDATE="true"; shift ;;
        *) log_warn "Unknown arg: $1"; shift ;;
    esac
done
GPU_COUNT="${TP_SIZE}"
export NODE_INSTANCE_TYPE TP_SIZE GPU_COUNT MODEL_FOLDER SERVED_NAME

echo ""
echo "=================================================="
echo "  DEPLOYING - {{hf_id}}"
echo "  Deployment    : ${DEPLOYMENT_NAME}"
echo "  Service       : ${SERVICE_NAME}:8000"
echo "  Namespace     : ${BENCHMARK_NAMESPACE}"
echo "  Instance type : ${NODE_INSTANCE_TYPE}   (TP=${TP_SIZE}, GPUs=${GPU_COUNT})"
echo "=================================================="
echo ""

log_info "Checking model in S3..."
if ! aws s3 ls "s3://${MODEL_BUCKET}/${MODEL_FOLDER}/" --region "${AWS_REGION}" >/dev/null 2>&1; then
    log_error "Model not found: s3://${MODEL_BUCKET}/${MODEL_FOLDER}/"
    log_error "Download it first: oai download {{id}}   (or bash model-download/{{id}}/download.sh)"
    exit 1
fi
log_info "Model found in S3."

log_info "Applying PVC..."
kubectl apply -f "${SCRIPT_DIR}/pvc.yaml"

log_info "Applying service: ${SERVICE_NAME}..."
kubectl apply -f "${SCRIPT_DIR}/service.yaml"

log_info "Applying deployment: ${DEPLOYMENT_NAME} on ${NODE_INSTANCE_TYPE}..."
export MODEL_BUCKET BENCHMARK_NAMESPACE VLLM_IMAGE
envsubst '${MODEL_BUCKET} ${BENCHMARK_NAMESPACE} ${VLLM_IMAGE} ${MODEL_FOLDER} ${SERVED_NAME} ${NODE_INSTANCE_TYPE} ${TP_SIZE} ${GPU_COUNT}' \\
    < "${SCRIPT_DIR}/deployment.yaml" | kubectl apply -f -

log_info "Waiting for pod (Karpenter provisioning ${NODE_INSTANCE_TYPE} ~2-4 min)..."
sleep 10
for i in $(seq 1 24); do
    POD=$(kubectl get pods -l app="${DEPLOYMENT_NAME}" -n "${BENCHMARK_NAMESPACE}" \\
        -o jsonpath='{.items[0].metadata.name}' 2>/dev/null || true)
    [[ -n "${POD}" ]] && break
    echo -n "."
    sleep 5
done
echo ""
log_info "Pod: ${POD:-not found yet}"

log_info "Waiting for Ready (model loading from S3 - up to 10 min)..."
kubectl wait "deployment/${DEPLOYMENT_NAME}" \\
    --for=condition=Available --timeout=600s -n "${BENCHMARK_NAMESPACE}" || {
    log_warn "Deployment not ready yet - check logs:"
    log_warn "  kubectl logs deployment/${DEPLOYMENT_NAME} -n ${BENCHMARK_NAMESPACE} | tail -30"
}

echo ""
echo "=================================================="
echo "  DEPLOYED - {{id}} on ${NODE_INSTANCE_TYPE}"
echo "=================================================="
kubectl get pods -l app="${DEPLOYMENT_NAME}" -n "${BENCHMARK_NAMESPACE}" -o wide
echo ""
echo "  Port-forward:"
echo "    kubectl port-forward svc/${SERVICE_NAME} ${PORT_FORWARD_PORT}:8000 -n ${BENCHMARK_NAMESPACE} &"
echo "    curl http://localhost:${PORT_FORWARD_PORT}/health"
echo "=================================================="

if [[ "${VALIDATE}" == "true" ]]; then
    echo ""
    log_info "Starting post-deploy validation (--validate flag set)..."
    bash "${SCRIPT_DIR}/../post-deploy-validate.sh" \\
        --model "${MODEL_ID}" \\
        --manifest "${MANIFEST_PATH}" \\
        --endpoint "http://${SERVICE_NAME}:8000"
fi
"""

STOP_SH = """\
#!/bin/bash
# ==============================================================================
# vllm/models/{{id}}/stop.sh  - GENERATED by `oai model generate {{id}}`
#
# Full teardown for {{id}}. Deletes the deployment/service/PVC and terminates
# THIS model's GPU node so billing stops. Leaves S3 weights and monitoring alone.
#
# Friendly wrapper:  oai stop {{id}}
# ==============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FRAMEWORK_ROOT="$(cd "${SCRIPT_DIR}/../../.." && pwd)"
source "${FRAMEWORK_ROOT}/config/config.env"
source "${SCRIPT_DIR}/model.env"
source "${FRAMEWORK_ROOT}/vllm/lib/gpu-terminate.sh"

GREEN='\\033[0;32m'; YELLOW='\\033[1;33m'; NC='\\033[0m'
log_info()  { echo -e "${GREEN}[INFO]  $(date +'%H:%M:%S')${NC} $1"; }
log_warn()  { echo -e "${YELLOW}[WARN]  $(date +'%H:%M:%S')${NC} $1"; }

echo ""
echo "=================================================="
echo "  FULL STOP - ${MODEL_ID}"
echo "  Deployment : ${DEPLOYMENT_NAME}"
echo "  Namespace  : ${BENCHMARK_NAMESPACE}"
echo "=================================================="
echo ""
echo "  This will:"
echo "    - Delete vLLM deployment, service, PVC"
echo "    - Terminate GPU node for this model (stops billing)"
echo "    - Clean up benchmark jobs for this model only"
echo "    - Leave monitoring stack running"
echo ""

if [[ "${OAI_ASSUME_YES:-false}" != "true" ]]; then
    read -r -p "Proceed? [y/N]: " CONFIRM
    [[ "${CONFIRM}" =~ ^[yY]$ ]] || { log_info "Cancelled."; exit 0; }
fi

log_info "Looking up node for deployment: ${DEPLOYMENT_NAME}..."
MODEL_NODE=$(kubectl get pod -l "app=${DEPLOYMENT_NAME}" -n "${BENCHMARK_NAMESPACE}" \\
    -o jsonpath='{.items[0].spec.nodeName}' 2>/dev/null || true)
[[ -n "${MODEL_NODE}" ]] && log_info "Model is running on node: ${MODEL_NODE}" || \\
    log_warn "Pod not found - node will be located via nodeclaim instance type."

log_info "Deleting deployment: ${DEPLOYMENT_NAME}..."
kubectl delete deployment "${DEPLOYMENT_NAME}" -n "${BENCHMARK_NAMESPACE}" --ignore-not-found=true
log_info "Deleting service: ${SERVICE_NAME}..."
kubectl delete svc "${SERVICE_NAME}" -n "${BENCHMARK_NAMESPACE}" --ignore-not-found=true
log_info "Deleting PVC: ${PVC_NAME}..."
kubectl delete pvc "${PVC_NAME}" -n "${BENCHMARK_NAMESPACE}" --ignore-not-found=true 2>/dev/null || true

terminate_model_gpu_node "${DEPLOYMENT_NAME}" "${BENCHMARK_NAMESPACE}" "${MODEL_NODE:-}"

log_info "Cleaning up benchmark jobs for model '${MODEL_ID}'..."
kubectl delete jobs -n "${BENCHMARK_NAMESPACE}" \\
    -l "app.kubernetes.io/component=benchmark-runner,model=${MODEL_ID}" \\
    --ignore-not-found=true 2>/dev/null || true

print_stop_summary "${MODEL_ID}" "${BENCHMARK_NAMESPACE}"
"""
