"""
Benchmark run-manifest template (shared).

Produces configs/manifests/<id>-<hw>-<quant>.yaml - the file the benchmark
harness (inference/load-test.py) reads. Every field here drives a run; nothing
is hardcoded in the harness. This is what makes benchmarking easily customizable:
edit the catalog (or this generated manifest) and re-run.
"""

MANIFEST_YAML = """\
# ==============================================================================
# configs/manifests/{{manifest_filename}}  - GENERATED by `oai model generate {{id}}`
#
# Benchmark run manifest for {{hf_id}} ({{quantization}}) on {{preferred_instance}}.
# Edit catalog/models/{{id}}.yaml and re-generate, or tweak this file directly for
# a one-off run. Every field is read by inference/load-test.py.
# ==============================================================================
run_id: {{run_id}}
description: "{{hf_id}} {{quantization}}, {{preferred_instance}}"

model:
  hf_id: {{hf_id}}
  served_name: {{served_name}}
  tokenizer: {{tokenizer}}
  s3_prefix: {{model_folder}}/
  source: {{manifest_source}}

serving:
  image: {{serving_image}}
  nodepool: {{nodepool}}
  instance_type: {{preferred_instance}}

optimization_variants:
  - label: {{quantization}}-{{hw_short}}
    quantization: {{quantization}}
    tensor_parallel_size: {{tp_or_cores}}
    max_num_seqs: {{max_num_seqs}}
    max_num_batched_tokens: {{max_num_batched_tokens}}
    max_model_len: {{max_model_len}}
    kv_cache_dtype: auto

benchmark:
  workload_profiles:
{{profiles_block}}

cost:
  instance_hourly_usd: {{instance_hourly_usd}}    # VERIFY before run

tags:
  Project: observeai-inference-optimization
  Engagement: shellkode-sow
  Environment: sandbox
  ManagedBy: oai-cli
  Owner: {{tag_owner}}
  CostCenter: {{tag_cost_center}}
  RunId: {{run_id}}
"""
