"""
Benchmark run-manifest template (shared).

Produces configs/manifests/<id>-<hw>-<quant>.yaml - the file the benchmark
harness (inference/load-test.py) reads. Every field here drives a run; nothing
is hardcoded in the harness. This is what makes benchmarking easily customizable:
edit the catalog (or this generated manifest) and re-run.
"""

MANIFEST_YAML = """\
# ==============================================================================
# configs/manifests/{{manifest_filename}}  - GENERATED by `oai model generate {{id}}`
#
# Benchmark run manifest for {{hf_id}} ({{quantization}}) on {{preferred_instance}}.
# Edit catalog/models/{{id}}.yaml and re-generate, or tweak this file directly for
# a one-off run. Every field is read by inference/load-test.py.
# ==============================================================================
run_id: {{run_id}}
description: "{{hf_id}} {{quantization}}, {{preferred_instance}}"

model:
  hf_id: {{hf_id}}
  served_name: {{served_name}}
  tokenizer: {{tokenizer}}
  s3_prefix: {{model_folder}}/
  source: {{manifest_source}}

serving:
  image: {{serving_image}}
  nodepool: {{nodepool}}
  instance_type: {{preferred_instance}}

optimization_variants:
  - label: {{quantization}}-{{hw_short}}
    quantization: {{quantization}}
    tensor_parallel_size: {{tp_or_cores}}
    max_num_seqs: {{max_num_seqs}}
    max_num_batched_tokens: {{max_num_batched_tokens}}
    max_model_len: {{max_model_len}}
    kv_cache_dtype: auto

benchmark:
  workload_profiles:
{{profiles_block}}

cost:
  instance_hourly_usd: {{instance_hourly_usd}}    # VERIFY before run

tags:
  Project: observeai-inference-optimization
  Engagement: shellkode-sow
  Environment: sandbox
  ManagedBy: oai-cli
  Owner: {{tag_owner}}
  CostCenter: {{tag_cost_center}}
  RunId: {{run_id}}
"""


# GPU manifest — ONE file per model for ALL NVIDIA G instances. Written to
# configs/manifests/<id>-gpu.yaml. The actual instance + cost resolve DYNAMICALLY
# at run time from --hw (OAI_INSTANCE_TYPE) against the EC2 price book in
# load-test.py, so a single manifest covers g5/g6/g6e/g7/g7e (any size). No static
# cost is written (dynamic); serving.instance_type is only a fallback label.
GPU_MANIFEST_YAML = """\
# ==============================================================================
# configs/manifests/{{id}}-gpu.yaml  - GENERATED by `oai model generate {{id}}`
#
# Single DYNAMIC GPU manifest for {{hf_id}} ({{quantization}}) — covers ALL NVIDIA
# G instances (g5 / g6 / g6e / g7 / g7e, any size). The instance is chosen at
# deploy time via `--hw`; instance_type, cost, and node placement resolve
# DYNAMICALLY (OAI_INSTANCE_TYPE from --hw → EC2 price book in load-test.py).
# serving.instance_type below is only a FALLBACK label for direct runs with no --hw.
# For Trainium/Neuron, use the separate <id>-neuron-*.yaml manifest (--manifest).
# Edit catalog/models/{{id}}.yaml and re-generate. Every field is read by inference/load-test.py.
# ==============================================================================
run_id: {{run_id}}
description: "{{hf_id}} {{quantization}}, any NVIDIA G instance (TP={{tp_or_cores}})"

model:
  hf_id: {{hf_id}}
  served_name: {{served_name}}
  tokenizer: {{tokenizer}}
  s3_prefix: {{model_folder}}/
  source: {{manifest_source}}

serving:
  image: {{serving_image}}
  # Fallback default only. Real instance comes from --hw (OAI_INSTANCE_TYPE);
  # node placement is by nodeSelector on this instance type at deploy time.
  instance_type: {{preferred_instance}}

optimization_variants:
  - label: {{quantization}}-gpu
    quantization: {{quantization}}
    tensor_parallel_size: {{tp_or_cores}}
    max_num_seqs: {{max_num_seqs}}
    max_num_batched_tokens: {{max_num_batched_tokens}}
    max_model_len: {{max_model_len}}
    kv_cache_dtype: auto

benchmark:
  workload_profiles:
{{profiles_block}}

# cost.instance_hourly_usd is resolved DYNAMICALLY at run time from the deployed
# instance (OAI_INSTANCE_TYPE / serving.instance_type) against the EC2 price book
# in load-test.py. Set an explicit value here ONLY to override (spot, savings plan).

tags:
  Project: observeai-inference-optimization
  Engagement: shellkode-sow
  Environment: sandbox
  ManagedBy: oai-cli
  Owner: {{tag_owner}}
  CostCenter: {{tag_cost_center}}
  RunId: {{run_id}}
"""
