"""
Neuron (AWS Trainium / Inferentia via vLLM-Neuron) template set.

Reproduces the concrete, hardened Neuron path (compile-once / serve-many):
  - model.env with SOURCE_FOLDER (bf16 input) + NEFF cache folder + neuron cores
  - compile-job.yaml: optimum-cli export neuron -> NEFF artifacts cached in S3
  - deployment.yaml: init container syncs weights S3->/model, vLLM-Neuron serves
  - service.yaml (ClusterIP)
  - deploy.sh (--compile / --cores / --managed-ng / --validate) and stop.sh

Per-model values are {{placeholders}}; deploy-time envsubst variables are intact.
Neuron supports fp16/bf16 only - enforced by catalog validation, not here.
"""

MODEL_ENV = """\
# ==============================================================================
# vllm/models/{{id}}/model.env  - GENERATED by `oai model generate {{id}}`
#
# Neuron / Trainium serving path. Edit catalog/models/{{id}}.yaml and re-generate.
#
# Workflow: first deploy with --compile (produces NEFF cache in S3), then every
# later deploy reuses the cache and starts fast.
#
#   oai deploy {{id}} --compile      # first time
#   oai deploy {{id}}                # subsequent (fast)
# ==============================================================================

export MODEL_ID="{{id}}"
export MODEL_HF_ID="{{hf_id}}"

# S3 folder with the raw bf16 weights - compile job INPUT.
export SOURCE_FOLDER="{{source_folder}}"
# S3 folder that holds the model the deployment serves from.
export MODEL_FOLDER="{{model_folder}}"
# S3 folder for compiled NEFF artifacts.
export NEFF_FOLDER="{{neff_folder}}"

export SERVED_NAME="{{served_name}}"
export MODEL_S3_PATH="s3://${MODEL_BUCKET}/${MODEL_FOLDER}/"

export DEPLOYMENT_NAME="{{deployment_name}}"
export SERVICE_NAME="{{service_name}}"

# ── Hardware defaults ─────────────────────────────────────────────────────────
export NEURON_INSTANCE_TYPE="{{preferred_instance}}"
# NEURON_CORES = tensor-parallel degree; must equal the compile-time value.
export NEURON_CORES="{{neuron_cores}}"

# Compile-time bucket parameters - must match compile-job.yaml.
export SEQ_LEN="{{sequence_length}}"
export BATCH_SIZE="{{batch_size}}"

export MANIFEST_PATH="configs/manifests/{{manifest_filename}}"
export PORT_FORWARD_PORT="{{port_forward_port}}"

# ── Managed node group fallback (used with --managed-ng) ─────────────────────
export TRN2_NODEGROUP_NAME="{{node_group}}"
"""

SERVICE_YAML = """\
# GENERATED by `oai model generate {{id}}` - edit catalog/models/{{id}}.yaml instead.
apiVersion: v1
kind: Service
metadata:
  name: {{service_name}}
  namespace: {{namespace}}
  labels:
    app.kubernetes.io/name: {{service_name}}
    app.kubernetes.io/component: inference-server
    project: observeai-inference-optimization
    engagement: shellkode-sow
    environment: sandbox
    model: {{id}}
    source: neuron
spec:
  type: ClusterIP
  selector:
    app: {{service_name}}
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
"""

DEPLOYMENT_YAML = """\
# ==============================================================================
# vllm/models/{{id}}/deployment.yaml  - GENERATED by `oai model generate {{id}}`
#
# Neuron serve stage. An init container syncs bf16 weights S3 -> /model, then
# vLLM-Neuron serves from the local path (the Neuron DLC has no runai streamer).
#
# nodeSelector uses instance-family (Karpenter). For the managed node-group
# fallback see deployment-managed-ng.yaml (generated alongside this file).
#
# Runtime values injected via envsubst by deploy.sh:
#   ${BENCHMARK_NAMESPACE} ${NEURON_VLLM_IMAGE} ${MODEL_BUCKET}
#   ${MODEL_FOLDER} ${MODEL_HF_ID} ${SERVED_NAME} ${NEURON_CORES}
# ==============================================================================

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{deployment_name}}
  namespace: ${BENCHMARK_NAMESPACE}
  labels:
    app.kubernetes.io/name: {{deployment_name}}
    app.kubernetes.io/component: inference-server
    app.kubernetes.io/managed-by: oai-cli
    app.kubernetes.io/version: "{{id}}"
    project: observeai-inference-optimization
    engagement: shellkode-sow
    environment: sandbox
    model: {{id}}
    source: neuron
  annotations:
    checkov.io/skip1: "CKV_K8S_43=Image digest pinned in NEURON_VLLM_IMAGE via config/config.env"
    checkov.io/skip2: "CKV_K8S_14=Image tag pinned in NEURON_VLLM_IMAGE; static analysis cannot resolve envsubst"
    checkov.io/skip3: "CKV_K8S_15=imagePullPolicy IfNotPresent acceptable with pinned image"
    checkov.io/skip4: "CKV_K8S_40=runAsUser 1000 pending vLLM-Neuron UID compatibility test"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{deployment_name}}
  template:
    metadata:
      labels:
        app: {{deployment_name}}
        app.kubernetes.io/name: {{deployment_name}}
        app.kubernetes.io/component: inference-server
        project: observeai-inference-optimization
        engagement: shellkode-sow
        environment: sandbox
        model: {{id}}
        source: neuron
    spec:
      serviceAccountName: oai-infopt-serving-sa
      automountServiceAccountToken: false
      hostPID: false
      hostIPC: false
      hostNetwork: false

      nodeSelector:
        {{node_selector_key}}: {{node_selector_value}}

      tolerations:
        - key: aws.amazon.com/neuron
          operator: Exists
          effect: NoSchedule

      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/component: benchmark-runner
                topologyKey: kubernetes.io/hostname

      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault

      terminationGracePeriodSeconds: 180

      initContainers:
        - name: model-sync
          image: amazon/aws-cli:2.15.0
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash", "-c"]
          args:
            - |
              echo "Syncing weights from s3://${MODEL_BUCKET}/${MODEL_FOLDER}/ -> /model/"
              aws s3 sync "s3://${MODEL_BUCKET}/${MODEL_FOLDER}/" /model/ \\
                --region "${AWS_DEFAULT_REGION}" --no-progress
              echo "Sync complete. Files:"; ls -lh /model/
              test -f /model/config.json && echo "config.json OK" || { echo "ERROR: config.json missing"; exit 1; }
          env:
            - name: AWS_DEFAULT_REGION
              value: "{{aws_region}}"
            - name: MODEL_BUCKET
              value: "${MODEL_BUCKET}"
            - name: MODEL_FOLDER
              value: "${MODEL_FOLDER}"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
          resources:
            requests:
              cpu: "4"
              memory: "8Gi"
            limits:
              cpu: "8"
              memory: "16Gi"
          volumeMounts:
            - name: model-weights
              mountPath: /model

      containers:
        - name: vllm-neuron
          image: ${NEURON_VLLM_IMAGE}
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash", "-c"]
          args:
            - |
              echo "vLLM-Neuron serving  model=/model  cores=${NEURON_CORES}"
              NEURON_SKIP_EFA_AFFINITY=1 vllm serve /model \\
                --served-model-name "${SERVED_NAME}" \\
                --max-model-len {{max_model_len}} \\
                --max-num-batched-tokens {{max_num_batched_tokens}} \\
                --max-num-seqs {{max_num_seqs}} \\
                --tensor-parallel-size "${NEURON_CORES}" \\
                --block-size 8 \\
                --no-enable-prefix-caching \\
                --port 8000
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: HOME
              value: "/tmp"
            - name: USER
              value: "vllm"
            - name: MODEL_BUCKET
              value: "${MODEL_BUCKET}"
            - name: MODEL_FOLDER
              value: "${MODEL_FOLDER}"
            - name: SERVED_NAME
              value: "${SERVED_NAME}"
            - name: NEURON_CORES
              value: "${NEURON_CORES}"
            - name: NEURONX_CACHE
              value: "/tmp/neuronx_cache"
            - name: NEURON_RT_NUM_CORES
              value: "${NEURON_CORES}"
            - name: NEURON_COMPILE_CACHE_URL
              value: "/tmp/neuron-compiled-artifacts"
            - name: AWS_DEFAULT_REGION
              value: "{{aws_region}}"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
          resources:
            requests:
              cpu: "{{cpu_request}}"
              memory: "{{memory_request}}"
              aws.amazon.com/neuron: "{{neuron_device_count}}"
            limits:
              cpu: "{{cpu_limit}}"
              memory: "{{memory_limit}}"
              aws.amazon.com/neuron: "{{neuron_device_count}}"
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 600
            periodSeconds: 15
            failureThreshold: 480
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 720
            periodSeconds: 30
            failureThreshold: 10
            timeoutSeconds: 5
          volumeMounts:
            - name: model-weights
              mountPath: /model
            - name: dshm
              mountPath: /dev/shm
            - name: tmp
              mountPath: /tmp

      volumes:
        - name: model-weights
          emptyDir:
            sizeLimit: {{weights_scratch_gi}}Gi
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 16Gi
        - name: tmp
          emptyDir:
            sizeLimit: 100Gi
"""

# The managed-node-group deployment is identical except for the nodeSelector.
# The generator renders DEPLOYMENT_YAML twice with different node_selector_* values.

COMPILE_JOB_YAML = """\
# ==============================================================================
# vllm/models/{{id}}/compile-job.yaml  - GENERATED by `oai model generate {{id}}`
#
# Compiles {{hf_id}} (bf16) -> Neuron NEFF artifacts, cached in S3 so serving
# does not recompile every run. Compile parameters are LOCKED at compile time -
# changing cores/seq/batch requires a full recompile.
#
# Runtime values injected via envsubst by deploy.sh:
#   ${BENCHMARK_NAMESPACE} ${DOWNLOAD_SERVICE_ACCOUNT}
#   ${MODEL_BUCKET} ${AWS_REGION} ${NEURON_COMPILE_IMAGE}
# ==============================================================================

apiVersion: batch/v1
kind: Job
metadata:
  name: {{compile_job_name}}
  namespace: ${BENCHMARK_NAMESPACE}
  labels:
    app.kubernetes.io/name: {{compile_job_name}}
    app.kubernetes.io/component: neuron-compile
    app.kubernetes.io/managed-by: oai-cli
    project: observeai-inference-optimization
    engagement: shellkode-sow
    environment: sandbox
    model: {{id}}
spec:
  backoffLimit: 1
  activeDeadlineSeconds: 43200
  ttlSecondsAfterFinished: 3600
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{compile_job_name}}
        app.kubernetes.io/component: neuron-compile
        project: observeai-inference-optimization
        engagement: shellkode-sow
        environment: sandbox
        model: {{id}}
    spec:
      restartPolicy: Never
      serviceAccountName: ${DOWNLOAD_SERVICE_ACCOUNT}
      automountServiceAccountToken: false
      hostPID: false
      hostIPC: false
      hostNetwork: false
      nodeSelector:
        eks.amazonaws.com/instance-family: {{instance_family}}
      tolerations:
        - key: aws.amazon.com/neuron
          operator: Exists
          effect: NoSchedule
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: neuron-compile
          image: ${NEURON_COMPILE_IMAGE}
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash", "-c"]
          args:
            - |
              set -euo pipefail
              SRC_FOLDER="{{source_folder}}"
              NEFF_FOLDER="{{neff_folder}}"
              NEURON_CORES="{{neuron_cores}}"
              SEQ_LEN="{{sequence_length}}"
              BATCH="{{batch_size}}"
              SRC_S3="s3://${MODEL_BUCKET}/${SRC_FOLDER}/"
              DST_S3="s3://${MODEL_BUCKET}/${NEFF_FOLDER}/"
              WORK_DIR="/tmp/model"; NEFF_DIR="/tmp/neff"

              echo "Compile {{id}}: ${SRC_S3} -> ${DST_S3} (cores=${NEURON_CORES}, seq=${SEQ_LEN}, batch=${BATCH})"

              echo "[1/4] Checking S3 NEFF cache..."
              if aws s3 ls "${DST_S3}" --region "${AWS_DEFAULT_REGION}" 2>/dev/null | grep -q .; then
                echo "NEFF cache already present at ${DST_S3} - skipping recompile."
                echo "Force recompile with: aws s3 rm ${DST_S3} --recursive"
                exit 0
              fi

              echo "[2/4] Syncing bf16 weights from S3..."
              mkdir -p "${WORK_DIR}" "${NEFF_DIR}"
              aws s3 sync "${SRC_S3}" "${WORK_DIR}/" --region "${AWS_DEFAULT_REGION}" --no-progress

              echo "[3/4] Installing optimum-neuron and compiling to NEFF..."
              pip install --quiet optimum-neuron
              export PATH="/tmp/.local/bin:${PATH}"
              optimum-cli export neuron \\
                --model "${WORK_DIR}" \\
                --sequence_length "${SEQ_LEN}" \\
                --batch_size "${BATCH}" \\
                --num_cores "${NEURON_CORES}" \\
                --auto_cast_type {{auto_cast_type}} \\
                --task text-generation \\
                "${NEFF_DIR}"

              echo "[4/4] Uploading NEFF artifacts to S3..."
              aws s3 sync "${NEFF_DIR}/" "${DST_S3}" --region "${AWS_DEFAULT_REGION}" --no-progress
              echo "Compile complete. NEFF at ${DST_S3}"
          env:
            - name: AWS_DEFAULT_REGION
              value: "${AWS_REGION}"
            - name: MODEL_BUCKET
              value: "${MODEL_BUCKET}"
            - name: NEURONX_CACHE
              value: "/tmp/neuronx_cache"
            - name: HOME
              value: "/tmp"
          securityContext:
            allowPrivilegeEscalation: false
            # false: pip install + neuronx-cc write to the filesystem during compile.
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
          resources:
            requests:
              cpu: "16"
              memory: "64Gi"
              aws.amazon.com/neuron: "{{neuron_device_count}}"
            limits:
              cpu: "32"
              memory: "128Gi"
              aws.amazon.com/neuron: "{{neuron_device_count}}"
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir:
            sizeLimit: 150Gi
"""

DEPLOY_SH = """\
#!/bin/bash
# ==============================================================================
# vllm/models/{{id}}/deploy.sh  - GENERATED by `oai model generate {{id}}`
#
# Deploys {{hf_id}} on AWS Trainium/Neuron via vLLM-Neuron.
# Friendly wrapper:  oai deploy {{id}} [--compile] [--managed-ng]
#
#   --compile     Run the compile job first (idempotent; first deploy only)
#   --cores N     Override NEURON_CORES (must match compile-time value)
#   --managed-ng  Use the managed node group instead of Karpenter
#   --validate    Smoke-test after ready
# ==============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FRAMEWORK_ROOT="$(cd "${SCRIPT_DIR}/../../.." && pwd)"
source "${FRAMEWORK_ROOT}/config/config.env"
source "${SCRIPT_DIR}/model.env"

: "${NEURON_VLLM_IMAGE:?ERROR: NEURON_VLLM_IMAGE is not set in config/config.env.}"
: "${NEURON_COMPILE_IMAGE:?ERROR: NEURON_COMPILE_IMAGE is not set in config/config.env.}"
: "${MODEL_BUCKET:?ERROR: MODEL_BUCKET is not set in config/config.env.}"
: "${BENCHMARK_NAMESPACE:?ERROR: BENCHMARK_NAMESPACE is not set in config/config.env.}"

GREEN='\\033[0;32m'; YELLOW='\\033[1;33m'; RED='\\033[0;31m'; NC='\\033[0m'
log_info()  { echo -e "${GREEN}[INFO]  $(date +'%H:%M:%S')${NC} $1"; }
log_warn()  { echo -e "${YELLOW}[WARN]  $(date +'%H:%M:%S')${NC} $1"; }
log_error() { echo -e "${RED}[ERROR] $(date +'%H:%M:%S')${NC} $1"; }

RUN_COMPILE="false"; VALIDATE="false"; USE_MANAGED_NG="false"
while [[ $# -gt 0 ]]; do
    case "$1" in
        --compile)    RUN_COMPILE="true"; shift ;;
        --cores)      NEURON_CORES="$2"; shift 2 ;;
        --validate)   VALIDATE="true"; shift ;;
        --managed-ng) USE_MANAGED_NG="true"; shift ;;
        *) log_warn "Unknown argument: $1"; shift ;;
    esac
done
export NEURON_CORES MODEL_FOLDER SERVED_NAME NEURON_VLLM_IMAGE NEURON_COMPILE_IMAGE

echo ""
echo "=============================================================="
echo "  DEPLOYING (Neuron) - {{hf_id}}"
echo "  Deployment    : ${DEPLOYMENT_NAME}"
echo "  Instance type : ${NEURON_INSTANCE_TYPE}   (NeuronCores=${NEURON_CORES})"
echo "  Compile first : ${RUN_COMPILE}   Managed-NG: ${USE_MANAGED_NG}"
echo "=============================================================="
echo ""

if [[ "${USE_MANAGED_NG}" == "true" && -n "${TRN2_NODEGROUP_NAME:-}" ]]; then
    log_info "Scaling up managed node group: ${TRN2_NODEGROUP_NAME} (desiredSize=1)..."
    aws eks update-nodegroup-config --cluster-name "${CLUSTER_NAME}" \\
        --nodegroup-name "${TRN2_NODEGROUP_NAME}" \\
        --scaling-config minSize=0,maxSize=1,desiredSize=1 --region "${AWS_REGION}" >/dev/null
    log_info "Waiting for node to join (~3-5 min)..."
    for i in $(seq 1 30); do
        TRN2_NODE=$(kubectl get nodes -l "eks.amazonaws.com/nodegroup=${TRN2_NODEGROUP_NAME}" \\
            -o jsonpath='{.items[0].metadata.name}' 2>/dev/null || true)
        [[ -n "${TRN2_NODE}" ]] && { log_info "Node: ${TRN2_NODE}"; break; }
        echo -n "."; sleep 10
    done
    echo ""
    [[ -n "${TRN2_NODE:-}" ]] && kubectl wait node "${TRN2_NODE}" --for=condition=Ready --timeout=300s || \\
        log_warn "Node not Ready yet - pod will wait."
fi

log_info "Checking bf16 source weights: s3://${MODEL_BUCKET}/${SOURCE_FOLDER}/"
if ! aws s3 ls "s3://${MODEL_BUCKET}/${SOURCE_FOLDER}/" --region "${AWS_REGION}" >/dev/null 2>&1; then
    log_error "Source weights not found. Download first: oai download {{id}}"
    exit 1
fi
log_info "Source weights found."

if [[ "${RUN_COMPILE}" == "true" ]]; then
    log_info "Submitting compile job (idempotent)..."
    export MODEL_BUCKET AWS_REGION DOWNLOAD_SERVICE_ACCOUNT BENCHMARK_NAMESPACE NEURON_COMPILE_IMAGE
    envsubst '${BENCHMARK_NAMESPACE} ${DOWNLOAD_SERVICE_ACCOUNT} ${MODEL_BUCKET} ${AWS_REGION} ${NEURON_COMPILE_IMAGE}' \\
        < "${SCRIPT_DIR}/compile-job.yaml" | kubectl apply -f -
    log_info "Waiting for compile job (up to 12h for MoE)..."
    kubectl wait job/{{compile_job_name}} --for=condition=Complete --timeout=43200s -n "${BENCHMARK_NAMESPACE}" || {
        log_error "Compile job failed. Logs: kubectl logs -f job/{{compile_job_name}} -n ${BENCHMARK_NAMESPACE}"
        exit 1
    }
    log_info "Compile complete."
fi

log_info "Applying service: ${SERVICE_NAME}..."
kubectl apply -f "${SCRIPT_DIR}/service.yaml"

export MODEL_BUCKET BENCHMARK_NAMESPACE NEURON_VLLM_IMAGE MODEL_FOLDER MODEL_HF_ID SERVED_NAME NEURON_CORES
if [[ "${USE_MANAGED_NG}" == "true" ]]; then
    DEPLOY_FILE="${SCRIPT_DIR}/deployment-managed-ng.yaml"
    log_info "Using managed node group deployment..."
else
    DEPLOY_FILE="${SCRIPT_DIR}/deployment.yaml"
fi
log_info "Applying deployment: ${DEPLOYMENT_NAME} (NeuronCores=${NEURON_CORES})..."
envsubst '${MODEL_BUCKET} ${BENCHMARK_NAMESPACE} ${NEURON_VLLM_IMAGE} ${MODEL_FOLDER} ${MODEL_HF_ID} ${SERVED_NAME} ${NEURON_CORES}' \\
    < "${DEPLOY_FILE}" | kubectl apply -f -

log_info "Waiting for pod..."
sleep 15
for i in $(seq 1 36); do
    POD=$(kubectl get pods -l "app=${DEPLOYMENT_NAME}" -n "${BENCHMARK_NAMESPACE}" \\
        -o jsonpath='{.items[0].metadata.name}' 2>/dev/null || true)
    [[ -n "${POD}" ]] && break
    echo -n "."; sleep 10
done
echo ""
log_info "Pod: ${POD:-not found yet}"

log_info "Waiting for Ready (up to 2h if compiling inside pod)..."
kubectl wait "deployment/${DEPLOYMENT_NAME}" --for=condition=Available --timeout=7200s -n "${BENCHMARK_NAMESPACE}" || {
    log_warn "Not ready yet - check: kubectl logs deployment/${DEPLOYMENT_NAME} -n ${BENCHMARK_NAMESPACE} --tail=50"
}

echo ""
echo "=============================================================="
echo "  DEPLOYED - {{id}} on ${NEURON_INSTANCE_TYPE}"
echo "=============================================================="
kubectl get pods -l "app=${DEPLOYMENT_NAME}" -n "${BENCHMARK_NAMESPACE}" -o wide
echo ""
echo "  Port-forward:"
echo "    kubectl port-forward svc/${SERVICE_NAME} ${PORT_FORWARD_PORT}:8000 -n ${BENCHMARK_NAMESPACE} &"
echo "=============================================================="

if [[ "${VALIDATE}" == "true" ]]; then
    log_info "Running post-deploy validation..."
    bash "${SCRIPT_DIR}/../post-deploy-validate.sh" \\
        --model "${MODEL_ID}" --manifest "${MANIFEST_PATH}" --endpoint "http://${SERVICE_NAME}:8000"
fi
"""

STOP_SH = """\
#!/bin/bash
# ==============================================================================
# vllm/models/{{id}}/stop.sh  - GENERATED by `oai model generate {{id}}`
#
# Stops {{id}} (Neuron). Deletes deployment/service and frees the Trainium node
# so billing stops. Leaves S3 weights, NEFF cache, and monitoring alone.
# Friendly wrapper:  oai stop {{id}}
# ==============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FRAMEWORK_ROOT="$(cd "${SCRIPT_DIR}/../../.." && pwd)"
source "${FRAMEWORK_ROOT}/config/config.env"
source "${SCRIPT_DIR}/model.env"

GREEN='\\033[0;32m'; YELLOW='\\033[1;33m'; NC='\\033[0m'
log_info()  { echo -e "${GREEN}[INFO]  $(date +'%H:%M:%S')${NC} $1"; }
log_warn()  { echo -e "${YELLOW}[WARN]  $(date +'%H:%M:%S')${NC} $1"; }

USE_MANAGED_NG="false"
while [[ $# -gt 0 ]]; do
    case "$1" in
        --managed-ng) USE_MANAGED_NG="true"; shift ;;
        *) shift ;;
    esac
done

echo ""
echo "=============================================================="
echo "  FULL STOP (Neuron) - ${MODEL_ID}"
echo "=============================================================="
echo ""

if [[ "${OAI_ASSUME_YES:-false}" != "true" ]]; then
    read -r -p "Proceed? [y/N]: " CONFIRM
    [[ "${CONFIRM}" =~ ^[yY]$ ]] || { log_info "Cancelled."; exit 0; }
fi

log_info "Deleting deployment: ${DEPLOYMENT_NAME}..."
kubectl delete deployment "${DEPLOYMENT_NAME}" -n "${BENCHMARK_NAMESPACE}" --ignore-not-found=true
log_info "Deleting service: ${SERVICE_NAME}..."
kubectl delete svc "${SERVICE_NAME}" -n "${BENCHMARK_NAMESPACE}" --ignore-not-found=true
log_info "Cleaning up compile job (if any)..."
kubectl delete job "{{compile_job_name}}" -n "${BENCHMARK_NAMESPACE}" --ignore-not-found=true

# Auto-detect managed node group if the name is set and the group exists.
if [[ -n "${TRN2_NODEGROUP_NAME:-}" ]]; then
    NG_STATUS=$(aws eks describe-nodegroup --cluster-name "${CLUSTER_NAME}" \\
        --nodegroup-name "${TRN2_NODEGROUP_NAME}" --region "${AWS_REGION}" \\
        --query 'nodegroup.status' --output text 2>/dev/null || true)
    [[ -n "${NG_STATUS}" && "${NG_STATUS}" != "None" ]] && USE_MANAGED_NG="true"
fi

if [[ "${USE_MANAGED_NG}" == "true" && -n "${TRN2_NODEGROUP_NAME:-}" ]]; then
    log_info "Scaling managed node group ${TRN2_NODEGROUP_NAME} to 0 (stops billing)..."
    aws eks update-nodegroup-config --cluster-name "${CLUSTER_NAME}" \\
        --nodegroup-name "${TRN2_NODEGROUP_NAME}" \\
        --scaling-config minSize=0,maxSize=1,desiredSize=0 --region "${AWS_REGION}" >/dev/null || \\
        log_warn "Could not scale node group - do it manually if needed."
else
    log_info "Locating Trainium node (Karpenter) for this deployment..."
    TRN_NODE=$(kubectl get pod -l "app=${DEPLOYMENT_NAME}" -n "${BENCHMARK_NAMESPACE}" \\
        -o jsonpath='{.items[0].spec.nodeName}' 2>/dev/null || true)
    if [[ -n "${TRN_NODE}" ]]; then
        log_info "Deleting node ${TRN_NODE} (Karpenter NodeClaim will be reclaimed)..."
        kubectl delete node "${TRN_NODE}" --ignore-not-found=true || log_warn "Node delete failed - check manually."
    else
        log_warn "No node found for this deployment - it may already be gone."
    fi
fi

echo ""
log_info "Stopped. S3 weights + NEFF cache preserved at s3://${MODEL_BUCKET}/${MODEL_FOLDER}/"
log_info "Safe to close your laptop."
"""
