#!/bin/bash
# ==============================================================================
# model-download/gpt-oss-20b-neuron/download.sh  - GENERATED by `oai model generate gpt-oss-20b-neuron`
#
# Downloads openai/gpt-oss-20b from HuggingFace -> S3. Friendly wrapper: oai download gpt-oss-20b-neuron
# Checks S3 first and skips if the model is already present.
# ==============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FRAMEWORK_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
source "${FRAMEWORK_ROOT}/config/config.env"

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'
log_info()  { echo -e "${GREEN}[INFO]  $(date +'%H:%M:%S')${NC} $1"; }
log_warn()  { echo -e "${YELLOW}[WARN]  $(date +'%H:%M:%S')${NC} $1"; }
log_error() { echo -e "${RED}[ERROR] $(date +'%H:%M:%S')${NC} $1"; }

MODEL_ID="openai/gpt-oss-20b"
MODEL_FOLDER="gpt-oss-20b"
JOB_NAME="oai-infopt-download-gpt-oss-20b-neuron"

echo ""
echo "=================================================="
echo "  MODEL DOWNLOAD - openai/gpt-oss-20b"
echo "  Bucket : s3://${MODEL_BUCKET}/${MODEL_FOLDER}/"
echo "  Token  : Required (gated model)"
echo "  Size   : ~40 GB"
echo "=================================================="
echo ""

log_info "Checking S3 for existing model files..."
if aws s3 ls "s3://${MODEL_BUCKET}/${MODEL_FOLDER}/" --region "${AWS_REGION}" 2>/dev/null | grep -q .; then
    log_warn "Model already exists in S3 - skipping download."
    aws s3 ls "s3://${MODEL_BUCKET}/${MODEL_FOLDER}/" --human-readable --region "${AWS_REGION}"
    exit 0
fi

log_info "Checking HuggingFace token secret..."
if ! kubectl get secret hf-token -n "${BENCHMARK_NAMESPACE}" >/dev/null 2>&1; then
    log_error "HuggingFace token secret not found (gated model)."
    log_error "Store it in Secrets Manager and sync via ESO, or create directly:"
    log_error "  kubectl create secret generic hf-token --from-literal=token=hf_YOURTOKEN -n ${BENCHMARK_NAMESPACE}"
    log_error "Also accept the license at: https://huggingface.co/openai/gpt-oss-20b"
    exit 1
fi
log_info "HF token secret found."

if ! kubectl get serviceaccount "${DOWNLOAD_SERVICE_ACCOUNT}" -n "${BENCHMARK_NAMESPACE}" >/dev/null 2>&1; then
    log_error "ServiceAccount '${DOWNLOAD_SERVICE_ACCOUNT}' not found. Run: bash cluster/bootstrap.sh"
    exit 1
fi

if kubectl get job "${JOB_NAME}" -n "${BENCHMARK_NAMESPACE}" >/dev/null 2>&1; then
    log_warn "Existing job '${JOB_NAME}' found - deleting..."
    kubectl delete job "${JOB_NAME}" -n "${BENCHMARK_NAMESPACE}"
    sleep 3
fi

log_info "Applying download job..."
export MODEL_BUCKET AWS_REGION DOWNLOAD_SERVICE_ACCOUNT BENCHMARK_NAMESPACE
envsubst '${MODEL_BUCKET} ${AWS_REGION} ${DOWNLOAD_SERVICE_ACCOUNT} ${BENCHMARK_NAMESPACE}' \
    < "${SCRIPT_DIR}/job.yaml" | kubectl apply -f -
log_info "Job '${JOB_NAME}' created."

log_info "Waiting for pod to start..."
for i in $(seq 1 30); do
    POD=$(kubectl get pods -l job-name="${JOB_NAME}" -n "${BENCHMARK_NAMESPACE}" \
        -o jsonpath='{.items[0].metadata.name}' 2>/dev/null || true)
    [[ -n "${POD}" ]] && break
    echo -n "."; sleep 5
done
echo ""
[[ -z "${POD:-}" ]] && { log_error "Pod not found. Check: kubectl get pods -l job-name=${JOB_NAME}"; exit 1; }
log_info "Pod: ${POD}"

log_info "Streaming logs (Ctrl+C to detach - job continues)..."
kubectl logs "${POD}" -n "${BENCHMARK_NAMESPACE}" -f 2>/dev/null || \
    kubectl logs "${POD}" -n "${BENCHMARK_NAMESPACE}" || true

log_info "Waiting for job to complete..."
kubectl wait job "${JOB_NAME}" --for=condition=complete --timeout=86400s -n "${BENCHMARK_NAMESPACE}" || {
    log_error "Job did not complete. Check: kubectl logs ${POD}"
    exit 1
}
log_info "Job completed."

log_info "Verifying S3 upload..."
aws s3 ls "s3://${MODEL_BUCKET}/${MODEL_FOLDER}/" --recursive --human-readable --region "${AWS_REGION}"

log_info "Cleaning up job..."
kubectl delete job "${JOB_NAME}" -n "${BENCHMARK_NAMESPACE}"

echo ""
echo "=================================================="
echo "  DOWNLOAD COMPLETE"
echo "  Model: s3://${MODEL_BUCKET}/${MODEL_FOLDER}/"
echo "  Next : oai deploy gpt-oss-20b-neuron"
echo "=================================================="
