"""
`oai` command-line interface.

The single entry point non-technical users interact with. Every command prints
plain-language progress and turns any failure into an actionable next step.

Commands:
  oai model new                 Interactive wizard to create a catalog entry
  oai model list                Table of onboarded models
  oai model validate <id>       Check a catalog entry (safe, read-only)
  oai model generate <id>       Write all deployment files from the catalog entry
  oai download <id>             Download weights from HuggingFace into S3
  oai deploy <id> [flags]       Deploy (auto-picks an instance); optional benchmark
  oai stop <id>                 Stop and free the accelerator node
  oai status                    Show what is running + rough cost
  oai benchmark <id> [flags]    Run the benchmark against a deployed model
"""

from __future__ import annotations

import argparse
import sys

from . import benchmark as bench_mod
from . import catalog, config, generate, instances, lifecycle, paths, shell, ui
from .ui import OaiError


# ---------------------------------------------------------------------------
# model subcommands
# ---------------------------------------------------------------------------
def _cmd_model_new(_args: argparse.Namespace) -> int:
    from . import wizard

    wizard.run()
    return 0


def _cmd_model_list(_args: argparse.Namespace) -> int:
    ids = catalog.list_ids()
    if not ids:
        ui.warn("No models onboarded yet.")
        ui.hint("Create one with 'oai model new' or copy catalog/TEMPLATE.yaml.")
        return 0
    ui.banner("Onboarded models")
    print(f"  {'ID':<24}{'HARDWARE':<10}{'QUANT':<8}{'GENERATED':<10}DISPLAY NAME")
    for mid in ids:
        try:
            spec = catalog.load(mid)
        except OaiError:
            print(f"  {mid:<24}{'?':<10}{'?':<8}{'?':<10}(invalid entry)")
            continue
        generated = "yes" if (paths.model_dir(mid) / "deploy.sh").exists() else "no"
        print(f"  {mid:<24}{spec.hardware:<10}{spec.serving.quantization:<8}{generated:<10}{spec.display_name}")
    return 0


def _cmd_model_validate(args: argparse.Namespace) -> int:
    spec = catalog.load(args.id)
    problems = catalog.validate(spec)
    ui.banner(f"Validate: {spec.id}")
    ui.kv("HuggingFace id", spec.source.hf_id)
    ui.kv("Hardware", spec.hardware)
    ui.kv("Instances", ", ".join(spec.instances.candidates) or "(none)")
    if not problems:
        ui.info("No problems found. This entry is ready to generate and deploy.")
        return 0
    ui.warn(f"Found {len(problems)} issue(s):")
    for p in problems:
        ui.hint(p)
    # Sizing/quant/instance problems are fatal; cost warning is not.
    fatal = [p for p in problems if "instance_hourly_usd is 0" not in p]
    return 1 if fatal else 0


def _cmd_model_generate(args: argparse.Namespace) -> int:
    spec = catalog.load(args.id)
    problems = [p for p in catalog.validate(spec) if "instance_hourly_usd is 0" not in p]
    if problems and not args.force:
        ui.error("Cannot generate - the catalog entry has problems:")
        for p in problems:
            ui.hint(p)
        ui.hint("Fix them, or re-run with --force to generate anyway.")
        return 1

    result = generate.generate(spec, force=args.force)
    ui.banner(f"Generate: {spec.id}")
    for f in result.created:
        ui.info(f"created  {f}")
    for f in result.updated:
        ui.info(f"updated  {f}")
    if result.unchanged:
        ui.step(f"{len(result.unchanged)} file(s) already up to date")
    if result.skipped_protected:
        ui.warn(f"{len(result.skipped_protected)} existing file(s) were NOT overwritten (not generated by oai):")
        for f in result.skipped_protected:
            ui.hint(f)
        ui.hint("Re-run with --force to overwrite them (this will lose manual edits).")
    ui.info(f"Done. Next: oai download {spec.id}  then  oai deploy {spec.id}")
    return 0


# ---------------------------------------------------------------------------
# lifecycle subcommands
# ---------------------------------------------------------------------------
def _cmd_download(args: argparse.Namespace) -> int:
    return lifecycle.download(args.id)


def _cmd_deploy(args: argparse.Namespace) -> int:
    return lifecycle.deploy(
        args.id,
        hw_override=args.hw,
        compile_first=args.compile,
        managed_ng=args.managed_ng,
        validate=args.validate,
        do_benchmark=args.benchmark,
        profile=args.profile,
        skip_instance_check=args.no_instance_check,
    )


def _cmd_stop(args: argparse.Namespace) -> int:
    return lifecycle.stop(args.id, managed_ng=args.managed_ng, assume_yes=args.yes)


def _cmd_status(_args: argparse.Namespace) -> int:
    return lifecycle.status()


def _cmd_benchmark(args: argparse.Namespace) -> int:
    return bench_mod.run(args.id, profile=args.profile, dataset=args.dataset, skip_batch=args.skip_batch)


# ---------------------------------------------------------------------------
# cluster subcommands
# ---------------------------------------------------------------------------
def _cmd_cluster_bootstrap(args: argparse.Namespace) -> int:
    from . import cluster as cluster_mod

    return cluster_mod.bootstrap(compute=args.compute, force=args.force)


def _cmd_cluster_setup_monitoring(args: argparse.Namespace) -> int:
    from . import cluster as cluster_mod

    return cluster_mod.setup_monitoring(force=args.force)


def _cmd_cluster_setup_neuron(args: argparse.Namespace) -> int:
    from . import cluster as cluster_mod

    return cluster_mod.setup_neuron(dry_run=args.dry_run, az=args.az, capacity_type=args.capacity_type)


def _cmd_cluster_teardown(args: argparse.Namespace) -> int:
    from . import cluster as cluster_mod

    return cluster_mod.teardown(assume_yes=args.yes)


def _cmd_cluster_status(_args: argparse.Namespace) -> int:
    from . import cluster as cluster_mod

    return cluster_mod.status()


# ---------------------------------------------------------------------------
# argument parser
# ---------------------------------------------------------------------------
def _build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="oai",
        description="ObserveAI inference framework - onboard, deploy, and benchmark models the easy way.",
    )
    sub = p.add_subparsers(dest="command", required=True)

    # model ...
    model = sub.add_parser("model", help="onboard and manage model catalog entries")
    msub = model.add_subparsers(dest="model_command", required=True)
    msub.add_parser("new", help="interactive wizard to create a catalog entry").set_defaults(func=_cmd_model_new)
    msub.add_parser("list", help="list onboarded models").set_defaults(func=_cmd_model_list)
    mv = msub.add_parser("validate", help="check a catalog entry")
    mv.add_argument("id")
    mv.set_defaults(func=_cmd_model_validate)
    mg = msub.add_parser("generate", help="write deployment files from a catalog entry")
    mg.add_argument("id")
    mg.add_argument("--force", action="store_true", help="overwrite files not generated by oai")
    mg.set_defaults(func=_cmd_model_generate)

    # download
    dl = sub.add_parser("download", help="download model weights from HuggingFace into S3")
    dl.add_argument("id")
    dl.set_defaults(func=_cmd_download)

    # deploy
    dp = sub.add_parser("deploy", help="deploy a model (auto-picks an available instance)")
    dp.add_argument("id")
    dp.add_argument("--hw", help="force a specific instance type (skips dynamic selection)")
    dp.add_argument("--compile", action="store_true", help="[neuron] run the compile job first")
    dp.add_argument("--managed-ng", action="store_true", help="[neuron] use the managed node group")
    dp.add_argument("--validate", action="store_true", help="run a smoke test after deploy")
    dp.add_argument("--benchmark", action="store_true", help="benchmark automatically after deploy")
    dp.add_argument("--profile", help="only run this workload profile (e.g. realtime_v1)")
    dp.add_argument(
        "--no-instance-check", action="store_true", help="skip the live availability check (use the preferred instance)"
    )
    dp.set_defaults(func=_cmd_deploy)

    # stop
    st = sub.add_parser("stop", help="stop a model and free its accelerator node")
    st.add_argument("id")
    st.add_argument("--managed-ng", action="store_true", help="[neuron] scale the managed node group to 0")
    st.add_argument("-y", "--yes", action="store_true", help="do not prompt for confirmation")
    st.set_defaults(func=_cmd_stop)

    # status
    sub.add_parser("status", help="show running models and rough cost").set_defaults(func=_cmd_status)

    # cluster ...
    cl = sub.add_parser("cluster", help="one-time cluster + monitoring setup")
    clsub = cl.add_subparsers(dest="cluster_command", required=True)

    cbs = clsub.add_parser("bootstrap", help="provision the EKS cluster (reuses it if it already exists)")
    cbs.add_argument("--compute", help="which pools to enable, e.g. 'gpu', 'gpu,g7', 'neuron', or 'all'")
    cbs.add_argument("--force", action="store_true", help="re-run even if the cluster already exists (reconcile)")
    cbs.set_defaults(func=_cmd_cluster_bootstrap)

    csm = clsub.add_parser("setup-monitoring", help="install Prometheus + Grafana + DCGM (reuse if present)")
    csm.add_argument("--force", action="store_true", help="re-run even if the stack is already installed")
    csm.set_defaults(func=_cmd_cluster_setup_monitoring)

    cns = clsub.add_parser(
        "setup-neuron", help="create (or reuse) the trn2 managed node group for Trainium models"
    )
    cns.add_argument("--az", help="pin an availability zone (otherwise auto-selected by capacity)")
    cns.add_argument("--capacity-type", choices=["spot", "on-demand"], help="spot (default) or on-demand")
    cns.add_argument("--dry-run", action="store_true", help="validate AZ/capacity only; create nothing")
    cns.set_defaults(func=_cmd_cluster_setup_neuron)

    ctd = clsub.add_parser("teardown", help="delete the EKS cluster (keeps S3 weights + IAM)")
    ctd.add_argument("-y", "--yes", action="store_true", help="skip the confirmation prompt")
    ctd.set_defaults(func=_cmd_cluster_teardown)

    clsub.add_parser("status", help="show cluster + monitoring + node-group health").set_defaults(
        func=_cmd_cluster_status
    )

    # benchmark
    bm = sub.add_parser("benchmark", help="benchmark a deployed model")
    bm.add_argument("id")
    bm.add_argument("--profile", help="only run this workload profile (e.g. batch_v1)")
    bm.add_argument("--dataset", help="custom dataset (s3://... or a key in the results bucket)")
    bm.add_argument("--skip-batch", action="store_true", help="run only the realtime profile")
    bm.set_defaults(func=_cmd_benchmark)

    return p


def main(argv: list[str] | None = None) -> int:
    parser = _build_parser()
    args = parser.parse_args(argv)
    try:
        return int(args.func(args))
    except OaiError as exc:
        ui.error(str(exc))
        if exc.hint_text:
            for line in exc.hint_text.splitlines():
                ui.hint(line.lstrip())
        return 1
    except KeyboardInterrupt:
        ui.warn("Interrupted.")
        return 130


if __name__ == "__main__":
    sys.exit(main())
