"""
Generator engine - turn a validated ModelSpec into all on-disk deployment files.

This is the heart of "onboard in one file": it reads the catalog entry and writes
the full hardened file set that a technical user would otherwise hand-write. It is
idempotent (safe to re-run) and reports exactly which files it created/updated,
plus a diff-friendly "unchanged" for files that already match.

Nothing here weakens security posture - the hardening lives in the templates and
is not parameterized.
"""

from __future__ import annotations

import datetime as _dt
import stat
from dataclasses import dataclass
from pathlib import Path

from . import config, paths, ui
from .catalog import ModelSpec
from .render import render
from .templates import download as t_dl
from .templates import gpu as t_gpu
from .templates import manifest as t_manifest
from .templates import neuron as t_neuron

# Port-forward ports are assigned deterministically from the id so two models
# never collide when port-forwarded at the same time.
_PORT_BASE = 8080


# Marker string present in every generated file. Used to detect whether an
# existing file is safe to overwrite (i.e. it was produced by us before).
_GEN_MARKER = "GENERATED by `oai model generate"


@dataclass
class GenResult:
    created: list[str]
    updated: list[str]
    unchanged: list[str]
    skipped_protected: list[str]

    def total(self) -> int:
        return len(self.created) + len(self.updated) + len(self.unchanged)


def _port_for(model_id: str) -> int:
    # Stable hash -> port in [8080, 8179]. Deterministic across runs.
    h = sum(ord(c) for c in model_id)
    return _PORT_BASE + (h % 100)


def _extra_args_block(extra_args: list[str]) -> str:
    if not extra_args:
        return "            # (no extra vLLM args)"
    return "\n".join(f'            - "{a}"' for a in extra_args)


def _profiles_block(profiles: list[str]) -> str:
    return "\n".join(f"    - {p}" for p in profiles)


def _ignore_patterns_literal(patterns: list[str]) -> str:
    if not patterns:
        return "None"
    inner = ", ".join(f"'{p}'" for p in patterns)
    return f"[{inner}]"


def _write(path: Path, content: str, executable: bool, result: GenResult, force: bool) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    rel = str(path.relative_to(paths.ROOT))
    if path.exists():
        old = path.read_text(encoding="utf-8")
        if old == content:
            result.unchanged.append(rel)
            return
        # Protect files not previously produced by this generator, unless forced.
        if _GEN_MARKER not in old and not force:
            result.skipped_protected.append(rel)
            return
        path.write_text(content, encoding="utf-8", newline="\n")
        result.updated.append(rel)
    else:
        path.write_text(content, encoding="utf-8", newline="\n")
        result.created.append(rel)
    if executable:
        try:
            mode = path.stat().st_mode
            path.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
        except OSError:
            pass  # Windows: chmod is a no-op; scripts run via `bash` anyway.


def _base_context(spec: ModelSpec, cfg: config.Config) -> dict[str, object]:
    namespace = cfg.get("BENCHMARK_NAMESPACE", "oai-infopt")
    aws_region = cfg.get("AWS_REGION", "us-east-2")
    run_id = f"{spec.id}-{_dt.date.today().isoformat()}-001"
    hw_short = spec.preferred_instance.split(".")[0] if spec.preferred_instance else spec.hardware
    return {
        "id": spec.id,
        "hf_id": spec.source.hf_id,
        "display_name": spec.display_name,
        "served_name": spec.serving.served_name,
        "tokenizer": spec.serving.tokenizer,
        "model_folder": spec.s3_model_folder,
        "deployment_name": spec.deployment_name,
        "service_name": spec.service_name,
        "pvc_name": spec.pvc_name,
        "download_job_name": spec.download_job_name,
        "compile_job_name": spec.compile_job_name,
        "namespace": namespace,
        "aws_region": aws_region,
        "preferred_instance": spec.preferred_instance,
        "tensor_parallel_size": spec.instances.tensor_parallel_size,
        "quantization": spec.serving.quantization,
        "max_model_len": spec.serving.max_model_len,
        "gpu_memory_utilization": spec.serving.gpu_memory_utilization,
        "max_num_seqs": spec.serving.max_num_seqs,
        "max_num_batched_tokens": spec.serving.max_num_batched_tokens,
        "cpu_request": spec.resources.cpu_request,
        "cpu_limit": spec.resources.cpu_limit,
        "memory_request": spec.resources.memory_request,
        "memory_limit": spec.resources.memory_limit,
        "size_gb": int(spec.source.size_gb) if spec.source.size_gb else "?",
        "manifest_filename": spec.manifest_filename,
        "port_forward_port": _port_for(spec.id),
        "extra_args_block": _extra_args_block(spec.serving.extra_args),
        "run_id": run_id,
        "hw_short": hw_short,
        "instance_hourly_usd": spec.benchmark.instance_hourly_usd,
        "profiles_block": _profiles_block(spec.benchmark.profiles),
        "tag_owner": spec.tags.get("Owner", "TBD"),
        "tag_cost_center": spec.tags.get("CostCenter", "TBD"),
    }


def _gen_gpu(spec: ModelSpec, ctx: dict[str, object], cfg: config.Config, result: GenResult, force: bool) -> None:
    mdir = paths.model_dir(spec.id)
    _write(mdir / "model.env", render(t_gpu.MODEL_ENV, ctx), False, result, force)
    _write(mdir / "service.yaml", render(t_gpu.SERVICE_YAML, ctx), False, result, force)
    _write(mdir / "pvc.yaml", render(t_gpu.PVC_YAML, ctx), False, result, force)
    _write(mdir / "deployment.yaml", render(t_gpu.DEPLOYMENT_YAML, ctx), False, result, force)
    _write(mdir / "deploy.sh", render(t_gpu.DEPLOY_SH, ctx), True, result, force)
    _write(mdir / "stop.sh", render(t_gpu.STOP_SH, ctx), True, result, force)

    # Manifest
    mctx = dict(ctx)
    mctx.update(
        {
            "manifest_source": "eks_gpu",
            "serving_image": cfg.get("VLLM_IMAGE", "${VLLM_IMAGE}"),
            "nodepool": "gpu-inf",
            "tp_or_cores": spec.instances.tensor_parallel_size,
        }
    )
    _write(paths.MANIFESTS_DIR / spec.manifest_filename, render(t_manifest.MANIFEST_YAML, mctx), False, result, force)


def _gen_neuron(spec: ModelSpec, ctx: dict[str, object], cfg: config.Config, result: GenResult, force: bool) -> None:
    assert spec.neuron is not None
    mdir = paths.model_dir(spec.id)
    # trn2.48xlarge exposes 16 neuron devices; request all to avoid the scheduler extender.
    device_count = 16 if spec.preferred_instance.startswith("trn2") else spec.instances.neuron_cores
    nctx = dict(ctx)
    nctx.update(
        {
            "source_folder": spec.neuron.source_folder,
            "neff_folder": spec.neuron.neff_folder,
            "sequence_length": spec.neuron.sequence_length,
            "batch_size": spec.neuron.batch_size,
            "auto_cast_type": spec.neuron.auto_cast_type,
            "instance_family": spec.neuron.instance_family,
            "neuron_cores": spec.instances.neuron_cores,
            "neuron_device_count": device_count,
            "node_group": spec.instances.node_group,
            "weights_scratch_gi": max(int(spec.source.size_gb * 1.5), 60) if spec.source.size_gb else 60,
        }
    )

    _write(mdir / "model.env", render(t_neuron.MODEL_ENV, nctx), False, result, force)
    _write(mdir / "service.yaml", render(t_neuron.SERVICE_YAML, nctx), False, result, force)

    # Karpenter deployment (instance-family selector)
    karpenter_ctx = dict(nctx)
    karpenter_ctx.update(
        {"node_selector_key": "eks.amazonaws.com/instance-family", "node_selector_value": spec.neuron.instance_family}
    )
    _write(mdir / "deployment.yaml", render(t_neuron.DEPLOYMENT_YAML, karpenter_ctx), False, result, force)

    # Managed node-group deployment (nodegroup selector) - only if a node group is named.
    if spec.instances.node_group:
        mng_ctx = dict(nctx)
        mng_ctx.update(
            {"node_selector_key": "eks.amazonaws.com/nodegroup", "node_selector_value": spec.instances.node_group}
        )
        _write(mdir / "deployment-managed-ng.yaml", render(t_neuron.DEPLOYMENT_YAML, mng_ctx), False, result, force)

    _write(mdir / "compile-job.yaml", render(t_neuron.COMPILE_JOB_YAML, nctx), False, result, force)
    _write(mdir / "deploy.sh", render(t_neuron.DEPLOY_SH, nctx), True, result, force)
    _write(mdir / "stop.sh", render(t_neuron.STOP_SH, nctx), True, result, force)

    # Manifest
    mctx = dict(nctx)
    mctx.update(
        {
            "manifest_source": "neuron",
            "serving_image": cfg.get("NEURON_VLLM_IMAGE", "${NEURON_VLLM_IMAGE}"),
            "nodepool": "neuron-inf",
            "tp_or_cores": spec.instances.neuron_cores,
        }
    )
    _write(paths.MANIFESTS_DIR / spec.manifest_filename, render(t_manifest.MANIFEST_YAML, mctx), False, result, force)


def _gen_download(spec: ModelSpec, ctx: dict[str, object], result: GenResult, force: bool) -> None:
    ddir = paths.download_dir(spec.id)
    # For neuron, the download folder is the bf16 SOURCE folder; for gpu it's the id folder.
    download_folder = spec.neuron.source_folder if (spec.is_neuron and spec.neuron) else spec.id
    dctx = dict(ctx)
    if spec.source.gated:
        dctx.update(
            {
                "token_label": "Required (gated model)",
                "token_check_block": render(t_dl.TOKEN_CHECK_GATED, ctx),
                "token_python_block": t_dl.TOKEN_PYTHON_GATED,
                "token_volume_mount": t_dl.TOKEN_VOLUME_MOUNT_GATED,
                "token_volume": t_dl.TOKEN_VOLUME_GATED,
                "token_security_note": t_dl.TOKEN_SECURITY_NOTE_GATED,
            }
        )
    else:
        dctx.update(
            {
                "token_label": "Not required (open model)",
                "token_check_block": t_dl.TOKEN_CHECK_OPEN,
                "token_python_block": t_dl.TOKEN_PYTHON_OPEN,
                "token_volume_mount": "",
                "token_volume": "",
                "token_security_note": "",
            }
        )
    dctx.update(
        {
            "download_folder": download_folder,
            "ignore_patterns": _ignore_patterns_literal(spec.source.ignore_patterns),
            "download_scratch_gi": max(int(spec.source.size_gb * 2.2), 30) if spec.source.size_gb else 30,
        }
    )
    _write(ddir / "download.sh", render(t_dl.DOWNLOAD_SH, dctx), True, result, force)
    _write(ddir / "job.yaml", render(t_dl.JOB_YAML, dctx), False, result, force)


def generate(spec: ModelSpec, force: bool = False) -> GenResult:
    """
    Generate all files for a model. Idempotent.

    Existing files that were NOT previously produced by this generator are left
    untouched and reported in `skipped_protected`, unless `force=True`. This keeps
    hand-curated models safe from accidental overwrite.
    """
    cfg = config.load()
    ctx = _base_context(spec, cfg)
    result = GenResult(created=[], updated=[], unchanged=[], skipped_protected=[])

    if spec.is_neuron:
        _gen_neuron(spec, ctx, cfg, result, force)
    else:
        _gen_gpu(spec, ctx, cfg, result, force)

    _gen_download(spec, ctx, result, force)
    return result
